spring:
  profiles:
    active: ${profile.active:dev} #默认加载application-dev.yml  本地环境配置文件默认加载测试环境数据库 testprod


#mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: com.titan.server.**.entity
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true

#Mybatis SQL打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.titan.server.**: debug
#    com.titan.server.**: info

# 线程池配置参数
task:
  pool:
    corePoolSize: 10 # 设置核心线程数
    maxPoolSize: 20  # 设置最大线程数
    keepAliveTime: 300 # 设置空闲线程存活时间（秒）
    queueCapacity: 100 # 设置队列容量
    threadNamePrefix: "-signpolicy-asynnotify-" # 设置线程名称前缀
    awaitTerminationSeconds: 60 #  设置线程池等待终止时间(秒)


#    com.titan.server.**: info
#  redis:
#    timeout: 10000ms
#    host: 39.102.65.157
#    port: 6379
#    database: 0 # 选择哪个库，默认0库
#    lettuce:
#      pool:
#        max-active: 1024 # 最大连接数，默认 8
#        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
#        max-idle: 200 # 最大空闲连接，默认 8
#        min-idle: 5
#  # rabbitmq配置
#  rabbitmq:
#    # 用户名
#    username: guest
#    # 密码
#    password: guest
#    # 服务器地址
#    host: 39.102.65.157
#    # 端口
#    port: 5672
#    # 消息失败回调
#    publisher-returns: true
#    # 消息确认回调
#    publisher-confirm-type: correlated